#ifndef ST7789_CONF_H
#define ST7789_CONF_H

#include "main.h"

/*
 * STM32F103C8T6 + ST7789 2.8" 240x320
 * Port adapted from the configuration style used by
 * Majid-Derhambakhsh/ST7789.
 *
 * Touch and SD are not used.
 */

/* SPI handle generated by CubeMX */
extern SPI_HandleTypeDef hspi1;
#define ST7789_SPI                  hspi1

/* GPIO mapping - change these if your board uses different pins */
#define ST7789_CS_GPIO_PORT         GPIOB
#define ST7789_CS_GPIO_PIN          GPIO_PIN_10

#define ST7789_DC_GPIO_PORT         GPIOB
#define ST7789_DC_GPIO_PIN          GPIO_PIN_0

#define ST7789_RST_GPIO_PORT        GPIOB
#define ST7789_RST_GPIO_PIN         GPIO_PIN_1

/* Full 240x320 panel */
#define ST7789_WIDTH                240U
#define ST7789_HEIGHT               320U

/*
 * Rotation:
 * 0 = portrait
 * 1 = landscape 320x240
 * 2 = portrait inverted
 * 3 = landscape inverted
 */
#define ST7789_ROTATION             1U

/*
 * Common full-size 240x320 ST7789 panels use 0,0.
 * If image is shifted, adjust here.
 */
#define ST7789_XSTART               0U
#define ST7789_YSTART               0U

#define ST7789_SPI_TIMEOUT          1000U

/*
 * Keep DMA disabled for first bring-up.
 * STM32F103C8T6 has limited RAM.
 *
 * After the LCD works reliably, DMA can be added.
 */
/* #define ST7789_USE_DMA */

#endif
